server:
  port: 8085

spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-jw2j8qyi.sql.tencentcdb.com:22321/homyit?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: ssnhmy123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 101.43.85.67
    port: 6380
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

file:
  save-path: /root/image/
  viewPath: /img/
pic:
  dir: /opt/img/
logging:
  level:
    cn.homyit.website.mapper: debug
